spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

fileUploadFolder: C:\Users\Claudio\IdeaProjects\fileUploadAndDownload\fileRepository